spring.application.name=GovindasStore


spring.datasource.url=jdbc:mysql://localhost:3306/GvindasStore
spring.datasource.username=root
spring.datasource.password=Password@134

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

